filebeat.modules:
- module: nginx
  access:
    var.paths: ["/tmp/nginx/access.log"]
  error:
    var.paths: ["/tmp/nginx/error.log"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"